server.port=8082
spring.application.name=fleet-vehicle-service
spring.profiles.active=${APP_PROFILE:dev}
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true