server.port=8082
spring.application.name=fleet-vehicle-service

# Redis Config
spring.data.redis.host=localhost
spring.data.redis.port=6379

# URL FIPE
fipe.api.url=https://parallelum.com.br/fipe/api/v1/carros/marcas

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest