spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}

fleet.vehicle.url=http://fleet-vehicle-service:8082/api/v1/vehicles