jwt.secret=46ab005d294acb42d46c3ae739046586f17cb158c07120fc3957eb30d621f34f

route.quote.url=${QUOTE_SERVICE_URL:http://localhost:8081}
route.vehicle.url=${VEHICLE_SERVICE_URL:http://localhost:8082}
route.auth.url=${AUTH_SERVICE_URL:http://localhost:8090}
route.document.url=${DOCUMENT_SERVICE_URL:http://localhost:8084}