server.port=8080
spring.application.name=fleet-gateway

spring.threads.virtual.enabled=true

jwt.secret=46ab005d294acb42d46c3ae739046586f17cb158c07120fc3957eb30d621f34f

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.swagger-ui.urls[0].name=1. Auth Service
springdoc.swagger-ui.urls[0].url=/api/v1/auth/v3/api-docs

springdoc.swagger-ui.urls[1].name=2. Quote Service
springdoc.swagger-ui.urls[1].url=/api/v1/quotes/v3/api-docs

springdoc.swagger-ui.urls[2].name=3. Vehicle Service
springdoc.swagger-ui.urls[2].url=/api/v1/vehicles/v3/api-docs