# PostgreSQL Local
spring.datasource.url=jdbc:postgresql://localhost:5432/fleet_auth_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT
jwt.expiration=3600000
jwt.secret=46ab005d294acb42d46c3ae739046586f17cb158c07120fc3957eb30d621f34f