# Server
server.port=8081
spring.application.name=fleet-quote-service
spring.profiles.active=${APP_PROFILE:test}
spring.jpa.open-in-view=false

springdoc.api-docs.path=/api/api-docs
springdoc.swagger-ui.path=/swagger-ui.html